version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itportal-v2
    ports:
      - "3000:3000"
    volumes:
      # Mount state file for persistence
      - ./backupec2_state.json:/app/backupec2_state.json
      # Mount raw data directory
      - ./raw-data:/app/raw-data
      # Mount AWS access key for SSH
      #- /home/sipparush/jventures-uat.pem:/app/jventures-uat.pem:ro
      - /home/jventures/.ssh:/home/node/.ssh
      # - ./.ssh:/app/.ssh
    environment:
      - NODE_ENV=production
      - AWS_PROFILE=aws_nonprod
      - AWS_REGION=ap-southeast-1
    env_file:
      - .env
    # Check if we need to set user explicitly if UID mismatch causes permission issues
    # user: "${UID}:${GID}" 
    restart: unless-stopped
